/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1mpVcJYIiYm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"


type ReviewCardProps = {
  name: string;
  role: string;
  rating: number;
  description: string;
  imageUrl: string;
};

export function ReviewCard({ name, role, rating, description ,imageUrl}: ReviewCardProps) {
  return (
  <Card className="w-full max-w-md bg-gray-700 border-slate-700 ">
    <div className="w-full max-w-md flex gap-10 justify-center pt-3">
  <div className="col-span-3 relative w-20 h-20 flex rounded-full overflow-hidden shrink-0">
    
    <img
      alt="Person"
      className="w-full h-auto object-cover rounded-full "
      src={imageUrl}
    />
  </div>

  <div className="col-span-9 flex flex-col  ">
    <div>
      <h3 className="text-xl font-semibold text-white dark:text-white">{name}</h3>
      <p className="text-white dark:text-white ">{role}</p>
      <div className="flex items-center gap-1 mt-2">
        {[...Array(5)].map((_, index) => (
          <StarIcon
            key={index}
            style={{
              borderColor: 'white'
            }}
            className={`w-7 h-7 ${index < Math.floor(rating) ? 'fill-amber-400 stroke-amber-400 dark:fill-gray-50 ' : 'fill-gray-100 stroke-gray-100 dark:fill-gray-800 dark:stroke-gray-400'}`}
          />
        ))}
        <span className="text-sm text-white dark:text-gray-400">{rating}</span>
      </div>
    </div>

     
  </div>
  </div>
  <p className="text-sm text-white dark:text-white mt-5 w-full p-3">
      {description}
    </p>

  
 
</Card>

  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}

